generobruno/FWOptimizer

- .gitignore
- README.md
- fwoptimizer/classes/__init__.py
- fwoptimizer/classes/parser.py
- fwoptimizer/classes/rules.py
- fwoptimizer/configs/syntaxes/iptables_syntax.py
- fwoptimizer/main.py
- fwoptimizer/utils/__init__.py
- fwoptimizer/utils/aliasDict.py
- pyproject.toml
- tests/conftest.py
- tests/test_set.txt
- tests/unit/test_parser.py
- Se modifico la estructura del proyecto para tratar tests con pytest.
- Se creó el archivo pyproject.toml
- Codigo de parser para probar estas configuraciones
> Mejoras en la estructura inicial

- fwoptimizer/utils/elementSet.py
- tests/unit/test_elementSet.py
Implementados ElementSetRegistry y ElementSet con sus subclases ProtSet y DirSet.
Generado test para ElementSetRegistry.
> ElementSet

- fwoptimizer/classes/fdd.py
- fwoptimizer/main.py
Se agregó la estructura para las clases mencionadas, utilizadas por FDD para las funciones del grafo.
> Node, Edge and Level strcuture

- .github/.pylintrc
- .github/annotate_pylint.py
- .github/annotate_pytest.py
- .github/workflows/main.yml
- .gitignore
- fwoptimizer/classes/__init__.py
- fwoptimizer/classes/fdd.py
- fwoptimizer/classes/firewall.py
- fwoptimizer/classes/parser.py
- fwoptimizer/classes/rules.py
- fwoptimizer/configs/syntaxes/__init__.py
- fwoptimizer/configs/syntaxes/iptables_syntax.py
- fwoptimizer/main.py
- fwoptimizer/utils/__init__.py
- fwoptimizer/utils/aliasDict.py
- fwoptimizer/utils/elementSet.py
- tests/conftest.py
- tests/unit/test_elementSet.py
- tests/unit/test_firewall.py
- tests/unit/test_parser.py
Arreglo de algunos errores de linter.
> Lint Errors

- fwoptimizer/classes/fdd.py
- fwoptimizer/classes/rules.py
- fwoptimizer/configs/syntaxes/iptables_syntax.py
- fwoptimizer/main.py
- fwoptimizer/utils/elementSet.py
- tests/unit/test_elementSet.py
- tests/unit/test_fdd.py
Implementado correctamente el genPre y una versión básica del printFDD.
Realizé cambios a varios módulos para que todo funcione.
Todavía debo cambiar el formato usado para las variables protegidas o privadas.
Agregé algunos test.
> Lucho algorithms

- fwoptimizer/classes/fdd.py
- fwoptimizer/classes/parser.py
- fwoptimizer/classes/rules.py
- fwoptimizer/main.py
- fwoptimizer/utils/elementSet.py
- tests/unit/test_fdd.py
1. Se implementó el algoritmo de FDD Reduction.
2. Se implementó el algoritmo de FDD Marking.
3. Se implementó el algoritmo de Firewall Generation and Compaction.
> Reduction n marking

- fwoptimizer/classes/fdd.py
- fwoptimizer/classes/rules.py
- fwoptimizer/main.py
- tests/unit/test_elementSet.py
Agregué defaultDecision a las chains.
Agregué el sanity step 3.
Cambié los nombres de las varialbes privadas en fdd.
Cambié el printFDD para que use el atributo label si existe en los edges.
Cree un nuevo método genFDD que lanza los métodos privados genPre y sanity 1-3. 
Si lo probas, vas a ver lo feo que queda el grafico. Si descomentas en sanityStep3 para que use el label se limpia un montón, pero no podes ver que hizo el step3.
Queda también pendiente definir una convención para los arcos que se saltean niveles del arbol y van directo a la decisión.
> Lucho fixes

- fwoptimizer/classes/fdd.py
- fwoptimizer/main.py
- fwoptimizer/utils/elementSet.py
> Hot fix - ElementSet.unionSet() and others

- .github/.pylintrc
- fwoptimizer/classes/fdd.py
- fwoptimizer/classes/parser.py
- fwoptimizer/classes/rules.py
- fwoptimizer/main.py
- fwoptimizer/utils/elementSet.py
1. Se corrigieron problemas con el algoritmo de compactación de reglas
2. Se generalizó el uso de predicados y elementSets
3. Se arreglaron algunos problemas del IpTablesParser
> FirewalGen fixes

- fwoptimizer/utils/elementSet.py
- tests/unit/test_elementSet.py
Añadida primera version funcional de PortSet
> added a functional first implementation of PortSet

- fwoptimizer/classes/fdd.py
- fwoptimizer/classes/parser.py
- fwoptimizer/classes/rules.py
- fwoptimizer/configs/syntaxes/iptables_syntax.py
- fwoptimizer/main.py
Se desarrolló la primera versión de la función compose de Parser (IPtablesParser), la cual toma un RuleSet y lo convierte a formato iptables-save.
> Reverse parser

- fwoptimizer/configs/fdd_config.toml
- fwoptimizer/main.py
- fwoptimizer/utils/elementSet.py
- pyproject.toml
- tests/test_fdd_config.toml
- tests/unit/test_elementSet.py
- tests/unit/test_fdd.py
- tests/unit/test_firewall.py
> Lucho portset

- fwoptimizer/classes/fdd.py
- fwoptimizer/main.py
Solucionado aparicion de dominio completo en algunos campos en firewall generation.
Solucionados problemas en firewall compaction
> Solved compaction algorithm problems

- fwoptimizer/classes/fdd.py
- fwoptimizer/classes/parser.py
- fwoptimizer/classes/rules.py
- fwoptimizer/main.py
- fwoptimizer/utils/elementSet.py
- tests/unit/test_equivalenceCheck.py
- tests/unit/test_parser.py
1. Se mejoró la visualización de los grafos.
2. Se implementarón funciones para resaltar caminos en el grafo.
1. Se implementaron funciones para comprobar la equivalencia entre cadenas (o Tablas de reglas) y encontrar sus diferencias en caso de que existan.
> Pretty Graph & Chain Equivalence

- fwoptimizer/classes/__init__.py
- fwoptimizer/classes/fdd.py
- fwoptimizer/classes/parser.py
- fwoptimizer/classes/rules.py
- fwoptimizer/main.py
- fwoptimizer/utils/elementSet.py
- tests/unit/test_chainComparator.py
- tests/unit/test_elementSet.py
- tests/unit/test_parser.py
Hice algunas pruebas y al parecer el algoritmo de comparacion esta funcionando correctamente.
Quedaría probar con ejemplos mejores y tambien borrar los metodos implementados para resolver la comparación de cadenas antes de usar ChainComparator
> Lucho general fix

- fwoptimizer/classes/fdd.py
Añadi el filtrado junto con una nueva función que se llama printFilteredFDD. Tuve que hacerla aparte porque sino se super complica la gestión de resetear los estados de los filtros.
> Added graph filtering functionality.

- fwoptimizer/controllers/fwoController.py
- fwoptimizer/views/dialogs.py
- fwoptimizer/views/fwoView.py
- fwoptimizer/views/mainView.py
- resources/interface.ui
Se agregaron funcionalidades a la GUI como:
- Funcionalidad de la pestaña "Home"
- Preguntar para guardar antes de cerrar
- Solución de errores varios
Entre otros
> Gui changes

- fwoptimizer/classes/fdd.py
No debería haber problemas en el merge, solo toque la funcion de filtrado inicial. 
Cuando mergees lo tuyo pensaba seguir modificando para que permita stackear filtrado
> Enhance filtering function

- fwoptimizer/classes/fdd.py
- fwoptimizer/classes/firewall.py
Añadi add rule aunque no inlcuí que haga automatico el reduction y el remarcado
> Lucho addrule feature

- fwoptimizer/classes/fdd.py
Allows stacking of multiple filters because it only checks those with visibility Compares elements as sets and not as strings
> New filter implementation:
